server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:8001/springbootsecurity?serverTimezone=Asia/Seoul
    username: root
    password: toor
    
  security:
    user:
      name: test
      password: 1234   
    oauth2:
      client:
        registration:          google:
            client-id: 862598267977-m2j7tkf7p40dsqam7dgjdkg5u95k2mga.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile 
          facebook:
            client-id: 930272064363071
            client-secret: b73a1ff759e743264487d3bd75a6bee1
            scope:
              - email
              - public_profile 
          naver:
            client-id: ITie0ihaGtKU6Zwl5mpa
            client-secret: TGPO3nAQxe
            scope:
              - email
              - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize  
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me 
              user-name-attribute: response #회원정보를 json으로 가지고 올때 response라는 key값으로 데이터를 전달해 준다.
              
mybatis:
  mapper-locations:
  - /mappers/*.xml